// protoc --proto_path=proto --go_out=. --go-grpc_out=. ./proto/pkv.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.18.1
// source: pkv.proto

package pkv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PkvMsgType int32

const (
	PkvMsgType_PREPARE PkvMsgType = 0
	PkvMsgType_ACCEPT  PkvMsgType = 1
	PkvMsgType_COMMIT  PkvMsgType = 2
)

// Enum value maps for PkvMsgType.
var (
	PkvMsgType_name = map[int32]string{
		0: "PREPARE",
		1: "ACCEPT",
		2: "COMMIT",
	}
	PkvMsgType_value = map[string]int32{
		"PREPARE": 0,
		"ACCEPT":  1,
		"COMMIT":  2,
	}
)

func (x PkvMsgType) Enum() *PkvMsgType {
	p := new(PkvMsgType)
	*p = x
	return p
}

func (x PkvMsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PkvMsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkv_proto_enumTypes[0].Descriptor()
}

func (PkvMsgType) Type() protoreflect.EnumType {
	return &file_pkv_proto_enumTypes[0]
}

func (x PkvMsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PkvMsgType.Descriptor instead.
func (PkvMsgType) EnumDescriptor() ([]byte, []int) {
	return file_pkv_proto_rawDescGZIP(), []int{0}
}

type InstanceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key     string `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Version int64  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
}

func (x *InstanceId) Reset() {
	*x = InstanceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InstanceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceId) ProtoMessage() {}

func (x *InstanceId) ProtoReflect() protoreflect.Message {
	mi := &file_pkv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceId.ProtoReflect.Descriptor instead.
func (*InstanceId) Descriptor() ([]byte, []int) {
	return file_pkv_proto_rawDescGZIP(), []int{0}
}

func (x *InstanceId) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *InstanceId) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ProposalNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	N          int64 `protobuf:"varint,1,opt,name=N,proto3" json:"N,omitempty"`
	ProposerId int64 `protobuf:"varint,2,opt,name=ProposerId,proto3" json:"ProposerId,omitempty"`
}

func (x *ProposalNum) Reset() {
	*x = ProposalNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProposalNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProposalNum) ProtoMessage() {}

func (x *ProposalNum) ProtoReflect() protoreflect.Message {
	mi := &file_pkv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProposalNum.ProtoReflect.Descriptor instead.
func (*ProposalNum) Descriptor() ([]byte, []int) {
	return file_pkv_proto_rawDescGZIP(), []int{1}
}

func (x *ProposalNum) GetN() int64 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ProposalNum) GetProposerId() int64 {
	if x != nil {
		return x.ProposerId
	}
	return 0
}

type Value struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V int64 `protobuf:"varint,1,opt,name=V,proto3" json:"V,omitempty"`
}

func (x *Value) Reset() {
	*x = Value{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkv_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_pkv_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_pkv_proto_rawDescGZIP(), []int{2}
}

func (x *Value) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

type PkvRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type PkvMsgType   `protobuf:"varint,1,opt,name=Type,proto3,enum=pkv.PkvMsgType" json:"Type,omitempty"`
	Id   *InstanceId  `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Rnd  *ProposalNum `protobuf:"bytes,3,opt,name=Rnd,proto3" json:"Rnd,omitempty"`
	Val  *Value       `protobuf:"bytes,4,opt,name=Val,proto3" json:"Val,omitempty"`
}

func (x *PkvRequest) Reset() {
	*x = PkvRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkv_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkvRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkvRequest) ProtoMessage() {}

func (x *PkvRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkv_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkvRequest.ProtoReflect.Descriptor instead.
func (*PkvRequest) Descriptor() ([]byte, []int) {
	return file_pkv_proto_rawDescGZIP(), []int{3}
}

func (x *PkvRequest) GetType() PkvMsgType {
	if x != nil {
		return x.Type
	}
	return PkvMsgType_PREPARE
}

func (x *PkvRequest) GetId() *InstanceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PkvRequest) GetRnd() *ProposalNum {
	if x != nil {
		return x.Rnd
	}
	return nil
}

func (x *PkvRequest) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

type PkvResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    PkvMsgType   `protobuf:"varint,1,opt,name=Type,proto3,enum=pkv.PkvMsgType" json:"Type,omitempty"`
	LastRnd *ProposalNum `protobuf:"bytes,2,opt,name=LastRnd,proto3" json:"LastRnd,omitempty"`
	Val     *Value       `protobuf:"bytes,3,opt,name=Val,proto3" json:"Val,omitempty"`
	VRnd    *ProposalNum `protobuf:"bytes,4,opt,name=VRnd,proto3" json:"VRnd,omitempty"`
}

func (x *PkvResponse) Reset() {
	*x = PkvResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkv_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PkvResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PkvResponse) ProtoMessage() {}

func (x *PkvResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkv_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PkvResponse.ProtoReflect.Descriptor instead.
func (*PkvResponse) Descriptor() ([]byte, []int) {
	return file_pkv_proto_rawDescGZIP(), []int{4}
}

func (x *PkvResponse) GetType() PkvMsgType {
	if x != nil {
		return x.Type
	}
	return PkvMsgType_PREPARE
}

func (x *PkvResponse) GetLastRnd() *ProposalNum {
	if x != nil {
		return x.LastRnd
	}
	return nil
}

func (x *PkvResponse) GetVal() *Value {
	if x != nil {
		return x.Val
	}
	return nil
}

func (x *PkvResponse) GetVRnd() *ProposalNum {
	if x != nil {
		return x.VRnd
	}
	return nil
}

var File_pkv_proto protoreflect.FileDescriptor

var file_pkv_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x6b, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x70, 0x6b, 0x76,
	0x22, 0x38, 0x0a, 0x0a, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4b, 0x65, 0x79,
	0x12, 0x18, 0x0a, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3b, 0x0a, 0x0b, 0x50, 0x72,
	0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x0c, 0x0a, 0x01, 0x4e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x4e, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x72, 0x6f, 0x70, 0x6f,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x50, 0x72, 0x6f,
	0x70, 0x6f, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x15, 0x0a, 0x05, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x0c, 0x0a, 0x01, 0x56, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x56, 0x22, 0x94,
	0x01, 0x0a, 0x0a, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6b,
	0x76, 0x2e, 0x50, 0x6b, 0x76, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1f, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f,
	0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x52,
	0x02, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x03, 0x52, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4e,
	0x75, 0x6d, 0x52, 0x03, 0x52, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x52, 0x03, 0x56, 0x61, 0x6c, 0x22, 0xa2, 0x01, 0x0a, 0x0b, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x6b, 0x76, 0x4d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x4c, 0x61,
	0x73, 0x74, 0x52, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6b,
	0x76, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x52, 0x07, 0x4c,
	0x61, 0x73, 0x74, 0x52, 0x6e, 0x64, 0x12, 0x1c, 0x0a, 0x03, 0x56, 0x61, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x03, 0x56, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x04, 0x56, 0x52, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x6f, 0x73, 0x61,
	0x6c, 0x4e, 0x75, 0x6d, 0x52, 0x04, 0x56, 0x52, 0x6e, 0x64, 0x2a, 0x31, 0x0a, 0x0a, 0x50, 0x6b,
	0x76, 0x4d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x50, 0x52, 0x45, 0x50,
	0x41, 0x52, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4d, 0x4d, 0x49, 0x54, 0x10, 0x02, 0x32, 0x93, 0x01,
	0x0a, 0x03, 0x50, 0x6b, 0x76, 0x12, 0x2e, 0x0a, 0x07, 0x50, 0x72, 0x65, 0x70, 0x61, 0x72, 0x65,
	0x12, 0x0f, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x10, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x06, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x12,
	0x0f, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x10, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x06, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x12, 0x0f,
	0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x10, 0x2e, 0x70, 0x6b, 0x76, 0x2e, 0x50, 0x6b, 0x76, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x70, 0x6b, 0x76, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkv_proto_rawDescOnce sync.Once
	file_pkv_proto_rawDescData = file_pkv_proto_rawDesc
)

func file_pkv_proto_rawDescGZIP() []byte {
	file_pkv_proto_rawDescOnce.Do(func() {
		file_pkv_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkv_proto_rawDescData)
	})
	return file_pkv_proto_rawDescData
}

var file_pkv_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkv_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkv_proto_goTypes = []interface{}{
	(PkvMsgType)(0),     // 0: pkv.PkvMsgType
	(*InstanceId)(nil),  // 1: pkv.InstanceId
	(*ProposalNum)(nil), // 2: pkv.ProposalNum
	(*Value)(nil),       // 3: pkv.Value
	(*PkvRequest)(nil),  // 4: pkv.PkvRequest
	(*PkvResponse)(nil), // 5: pkv.PkvResponse
}
var file_pkv_proto_depIdxs = []int32{
	0,  // 0: pkv.PkvRequest.Type:type_name -> pkv.PkvMsgType
	1,  // 1: pkv.PkvRequest.Id:type_name -> pkv.InstanceId
	2,  // 2: pkv.PkvRequest.Rnd:type_name -> pkv.ProposalNum
	3,  // 3: pkv.PkvRequest.Val:type_name -> pkv.Value
	0,  // 4: pkv.PkvResponse.Type:type_name -> pkv.PkvMsgType
	2,  // 5: pkv.PkvResponse.LastRnd:type_name -> pkv.ProposalNum
	3,  // 6: pkv.PkvResponse.Val:type_name -> pkv.Value
	2,  // 7: pkv.PkvResponse.VRnd:type_name -> pkv.ProposalNum
	4,  // 8: pkv.Pkv.Prepare:input_type -> pkv.PkvRequest
	4,  // 9: pkv.Pkv.Accept:input_type -> pkv.PkvRequest
	4,  // 10: pkv.Pkv.Commit:input_type -> pkv.PkvRequest
	5,  // 11: pkv.Pkv.Prepare:output_type -> pkv.PkvResponse
	5,  // 12: pkv.Pkv.Accept:output_type -> pkv.PkvResponse
	5,  // 13: pkv.Pkv.Commit:output_type -> pkv.PkvResponse
	11, // [11:14] is the sub-list for method output_type
	8,  // [8:11] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_pkv_proto_init() }
func file_pkv_proto_init() {
	if File_pkv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InstanceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProposalNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkv_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Value); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkv_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkvRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkv_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PkvResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkv_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkv_proto_goTypes,
		DependencyIndexes: file_pkv_proto_depIdxs,
		EnumInfos:         file_pkv_proto_enumTypes,
		MessageInfos:      file_pkv_proto_msgTypes,
	}.Build()
	File_pkv_proto = out.File
	file_pkv_proto_rawDesc = nil
	file_pkv_proto_goTypes = nil
	file_pkv_proto_depIdxs = nil
}
